### ISSUE TITLE
Base URL mis-spelled "airapir" vs correct "airpair"

### ISSUE THREAD

**Issue by danprime** [airpair/consult.airpair.com#49]
In http://consult.airpair.com/office under Migration Status sidebar, the link for Payouts and Recent Bookings are currently referring to "https://www.airapir.com/payouts" and "https://www.airapir.com/office"

note the misspelled airpair which causes a Server Not Found (not even a 404 as airapir.com does not exist as a domain).

**Comment by jkresner** [comment]
Thanks PR already merged, waiting to be deployed in v0.6.1 (hoping this week)
