### ISSUE TITLE
Existing oAuth breaks when a new profile has been found.

### ISSUE THREAD

**Issue by NoellyB76** [airpair/consult.airpair.com#54]
I went to add my new Twitter profile to AirPair. It's not actually new, just a changed name. So, the obvious way for me to do this is to go to Twitter and revoke oAuth app access for AirPair. That's all good and dandy.

The issue here is the error page that spat out server MEAN errors. :)

**Comment by jkresner** [comment]
Thanks - unlinking is now implemented - will have to thrown some ui in there over the next week or two.

https://github.com/jkresner/meanair-auth/blob/master/test/ex1-airpair/specs/link.coffee

**Comment by jkresner** [comment]
Ok - latest deploy comes with little crosses that can be used to unlink existing profiles:

![screen shot 2016-01-10 at 9 09 40 pm](https://cloud.githubusercontent.com/assets/979542/12221014/13b8bf60-b7de-11e5-8d70-e082403cde80.png)
