### ISSUE TITLE
Broken UI when PayPal account setup fails.

### ISSUE THREAD

**Issue by lukaslozovski** [airpair/consult.airpair.com#55]
When adding a PayPal account, one of the things that PayPal does is check to make sure that your account is verified. In my case, I didn't link a bank account to my PayPal account, and that makes my account unvirified.

Because of the PayPal rejection, the airpair UI ends up looking really broken, screenshot below: 
![screen shot 2015-12-17 at 2 52 37 pm](https://cloud.githubusercontent.com/assets/1127261/11880460/d6b9777a-a4ce-11e5-9723-cb5cf6cbda0d.png)

I was pointed at https://github.com/airpair/consult.airpair.com/blob/v0.6.1/server/routes/auth.js as a potential source of the issue.

**Comment by jkresner** [comment]
Turned out this was a new way the built assets were being passed to the render function of the error handler. This issues has been fixed but I'll leave it open because I'd like to return and do less hacky.

**Comment by jkresner** [comment]
Clean static solution now implemented for error pages across the different sub-domain apps. thanks :)

![screen shot 2016-02-02 at 8 45 20 pm](https://cloud.githubusercontent.com/assets/979542/12745446/60233030-c9ed-11e5-8ff1-d41e46b2eab4.png)
