### ISSUE TITLE
Linking to LinkedIn account fails

### ISSUE THREAD

**Issue by stupakov** [airpair/consult.airpair.com#56]
Attempting to link my LinkedIn account yields a 500.
Two subsequent attempts got two different error screens.

<img width="1673" alt="screen shot 2015-12-23 at 8 34 16 pm" src="https://cloud.githubusercontent.com/assets/164639/11989599/7715e3f8-a9b5-11e5-8022-91744e279e9a.png">

1st attempt:
<img width="1671" alt="screen shot 2015-12-23 at 8 34 05 pm" src="https://cloud.githubusercontent.com/assets/164639/11989600/7aa509c2-a9b5-11e5-9526-e4d7102af1fe.png">

after hitting "back" and trying again:
<img width="1673" alt="screen shot 2015-12-23 at 8 34 31 pm" src="https://cloud.githubusercontent.com/assets/164639/11989605/7e2886fa-a9b5-11e5-8164-eac5f220805c.png">

**Comment by jkresner** [comment]
Thanks in the queue!

**Comment by jkresner** [comment]
@stupakov just deployed a new release candidate. This issue turned out to be a copy and paste error with the ClientSecret config value :)
