### ISSUE TITLE
 Connected social accounts provides no forms to enter data

### ISSUE THREAD

**Issue by psygnisfive** [airpair/consult.airpair.com#62]
Step 1 of completing a profile for consulting says social accounts should be linked to the site, but there's no way to add them. In the account view on the main (non-consulting) portion of the site, there's mention of connected social accounts, but again no way to add them. It seems like something might not be loading. The JS consol doesn't report any errors, however.

Browser is Chrome Version 47.0.2526.106 (64-bit) on Mac OS El Capitan

**Comment by jkresner** [comment]
Thank you for sharing. Do you can a screenshot + can you include the browser console. Lots of other folks have been getting through the flow.

**Comment by psygnisfive** [comment]
![screen shot 2016-01-14 at 1 06 57 am](https://cloud.githubusercontent.com/assets/171941/12317061/3d0da7c0-ba5b-11e5-8468-8f5f44eb8216.png)

**Comment by jkresner** [comment]
Mind a huge favor exploring the network tab and doing shit + refresh? I feel like it's some temporary cnd / network issue.

![screen shot 2016-01-14 at 6 32 52 pm](https://cloud.githubusercontent.com/assets/979542/12318226/d235c3be-baec-11e5-99c1-26c7caab5cfb.png)
<img width="204" alt="screen shot 2016-01-14 at 6 33 03 pm" src="https://cloud.githubusercontent.com/assets/979542/12318227/d2378280-baec-11e5-93dc-9162b1648995.png">

**Comment by psygnisfive** [comment]
Here's the network panel from that shot, plus a refresh that produced the same thing. Additionally, on iOS things show up just fine.

![screen shot 2016-01-14 at 10 37 32 am](https://cloud.githubusercontent.com/assets/171941/12329056/6e029470-baac-11e5-8b1b-195d6cd8b7d6.png)
![screen shot 2016-01-14 at 10 38 35 am](https://cloud.githubusercontent.com/assets/171941/12329057/6e03cf2a-baac-11e5-8a37-5586adf6cfb6.png)

**Comment by jkresner** [comment]
Do you have any ad-blockers, interesting chrome extensions running?
ᐧ

On Fri, Jan 15, 2016 at 2:49 AM, Darryl McAdams <notifications@github.com>
wrote:

> Here's the network panel from that shot, plus a refresh that produced the
> same thing. Additionally, on iOS things show up just fine.
>
> [image: screen shot 2016-01-14 at 10 37 32 am]
> <https://cloud.githubusercontent.com/assets/171941/12329056/6e029470-baac-11e5-8b1b-195d6cd8b7d6.png>
> [image: screen shot 2016-01-14 at 10 38 35 am]
> <https://cloud.githubusercontent.com/assets/171941/12329057/6e03cf2a-baac-11e5-8a37-5586adf6cfb6.png>
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/airpair/consult.airpair.com/issues/62#issuecomment-171679360>
> .
>



-- 
*Jonathon Kresner*
*Co-founder, CEO*
@AirPair <http://twitter.com/airpair> | *airpair.com
<http://www.airpair.com>*
@hackerpreneur <http://twitter.com/hackerpreneur>

**Comment by psygnisfive** [comment]
On a hunch, I just checked if ABP could be the cause, and it was. It's not reporting any blocks, which is odd.

**Comment by psygnisfive** [comment]
oh, hah, I see you mentioned ad blockers :)

**Comment by jkresner** [comment]
Thanks for taking this time :)
