### ISSUE TITLE
Profile Page Not Loading in Firefox

### ISSUE THREAD

**Issue by snipertomcat** [airpair/consult.airpair.com#65]
I'm having an issue with the https://consult.airpair.com/profile/resume page loading in firefox. I just created an account and clicked the 'profiles' link. The page ends with the following message: 
"Connect at least 2 profiles to continue.", the rest of the screen is blank. 

I reloaded the page in chrome and it displayed the social media link buttons that were not loading in firefox.

**Comment by jkresner** [comment]
Is this relevant? https://github.com/airpair/consult.airpair.com/issues/62

**Comment by jkresner** [comment]
Firefox on my mac ...

![screen shot 2016-01-15 at 8 48 33 am](https://cloud.githubusercontent.com/assets/979542/12338566/4f4a966e-bb64-11e5-9bb0-262616135829.png)

**Comment by snipertomcat** [comment]
Yes [#62](https://github.com/airpair/consult.airpair.com/issues/62) was the exact issue I'm referring to, thank you!
