### ISSUE TITLE
Problem in submitting article

### ISSUE THREAD

**Issue by championswimmer** [airpair/consult.airpair.com#67]
```
GH.setToken fail. gh athr.token not present on [Arnav Gupta::563d0e37c8678011005ef386]
```

**Comment by Puigcerber** [comment]
I'm getting the same error when going to https://author.airpair.com/library.

**Comment by jkresner** [comment]
@Puigcerber | @championswimmer come back in 2 hours - you're gonna love it :) - mega version upgrade

![screen shot 2016-01-22 at 12 07 48 pm](https://cloud.githubusercontent.com/assets/979542/12529793/3421af5a-c17a-11e5-94b6-2721c299b607.png)
![screen shot 2016-01-22 at 12 11 22 pm](https://cloud.githubusercontent.com/assets/979542/12529792/341f8626-c17a-11e5-96dd-1fe6cc6bc9f8.png)

**Comment by Puigcerber** [comment]
Nice @jkresner! Looking forward to it.

**Comment by jkresner** [comment]
OK - just deployed @Puigcerber still need to do a little work around the stuff you want. Hopefully another few hours. This particular issue  should be fixed as it's a much newer version of the auth framework int this build.
