### ISSUE TITLE
Issue collecting payment - INSUFFICIENT_FUNDS

### ISSUE THREAD

**Issue by snipertomcat** [airpair/consult.airpair.com#71]
I've never seen this issue before, but it appears that when I go to collect a payment for work already completed, it gives me an INSUFFICIENT_FUNDS error. I'm not sure what this is about but it happens to be my last 2 payments for this contract. I'm eager to get these done and over with because I've put in some seriously out of control overtime the last few weeks but I've never seen this error before. 

I'm assuming that the hours were paid for by the person responsible for paying me consulting fees, but I'm not entirely sure what is going on at this point. Any help would be appreciated. Here is what the error message says:

Sender has insufficient funds => https://developer.paypal.com/webapps/developer/docs/api/#INSUFFICIENT_FUNDS

**Comment by jkresner** [comment]
Sorry I need to top up PayPal. Will take 5 bus days :(

On Thursday, February 25, 2016, Jesse Griffin <notifications@github.com>
wrote:

> I've never seen this issue before, but it appears that when I go to
> collect a payment for work already completed, it gives me an
> INSUFFICIENT_FUNDS error. I'm not sure what this is about but it happens to
> be my last 2 payments for this contract. I'm eager to get these done and
> over with because I've put in some seriously out of control overtime the
> last few weeks but I've never seen this error before.
>
> I'm assuming that the hours were paid for by the person responsible for
> paying me consulting fees, but I'm not entirely sure what is going on at
> this point. Any help would be appreciated. Here is what the error message
> says:
>
> Sender has insufficient funds =>
> https://developer.paypal.com/webapps/developer/docs/api/#INSUFFICIENT_FUNDS
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/airpair/consult.airpair.com/issues/71>.
>


-- 
*Jonathon Kresner*
*Co-founder, CEO*
@AirPair <http://twitter.com/airpair> | *airpair.com
<http://www.airpair.com>*
@hackerpreneur <http://twitter.com/hackerpreneur>

**Comment by snipertomcat** [comment]
Ah yes that would most certainly make sense. Thank you.

**Comment by jkresner** [comment]
Just an update - I thought I'd topped up Friday - but opened my computer first thing this morning and realized I was stuck on the confirmation screen. It's 100% gone through now, so 3-5 business days from here.
